### PR TITLE
fix(ListDatasets): Add support for multiple thumbnails

### PR DESCRIPTION
**Pull request by mathturtle**
When multiple thumbnails are provided, rotate through them.

@jourdain I'm not sure how to detect when the user has moused over a specific dataset's thumbnail to only do the thumbnail updates then...

### CODE REVIEW

**Comment by jourdain** [comment]
That seems good enough for now. ;-)

**Comment by mathturtle** [comment]
I added another commit that builds on this.  This one allows you to save thumbnails from the current view and adds them permanently to the dataset's json description for #6.  I'd like to make a popup that asks if you are sure you want to create the thumbnail and warns about the resize of the view, but I don't know which react-based modal dialog widget to use (there are about 5 on the first page of Google).  Do we have one we prefer for things like this?

**Comment by jourdain** [comment]
You can use 'prompt(...)' in pure Javascript.

**Comment by mathturtle** [comment]
Actually what I wanted was 'confirm(...)' from JavaScript.  But this makes npm run build give a warning:
`  52:9  warning  Unexpected confirm  no-alert`.  I don't know if we care about this or not.  I've pushed the new version with the confirm dialog.

**Comment by jourdain** [comment]
Just ESLint warning saying that won't work server side ;-)

**Pull request merged**
