### PR TITLE
fix(Contour): Contour uses the color by array as the array to contour by

### PR DESCRIPTION
**Pull request by mathturtle**
Fixes issue #1.

### CODE REVIEW

**Comment by jourdain** [comment]
lgtm

**Comment by mathturtle** [comment]
Is your automatic version creation software smart enough to ignore Github's merge commits or do I need to merge this on the command line and rebase my other branches?

**Comment by jourdain** [comment]
Not sure... What is the issue you noticed?

**Comment by mathturtle** [comment]
I hadn't noticed anything yet.  I was wondering if it would break things if I just hit 'Merge' on this one.

**Comment by mathturtle** [comment]
Let's find out.

**Pull request merged**
